#!/bin/bash
# clean out the images left behind docker containers
# careful as this cleans all indiscriminately
# https://github.com/docker/docker/blob/master/contrib/nuke-graph-directory.sh
docker rm `docker ps -a -q`
docker rmi -f `docker images -q`
