#!/bin/bash
if [[ $# -eq 0 ]] ; then
    echo "USAGE: $0 CLIENTNAME "
    echo 'where CLIENTNAME is a clientname to be used with the vpn'
    exit 0
fi
OVPN_DATA="ovpn-data"
CLIENTNAME=$1
docker run --volumes-from $OVPN_DATA --rm -it kylemanna/openvpn easyrsa build-client-full $CLIENTNAME nopass
docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_getclient $CLIENTNAME > $CLIENTNAME.ovpn
