#!/bin/bash
echo -n "Installing docker repos Ctrl-C now to exit"
for i in {1..5};do sleep 1; echo -n '!'; done
echo '!'
cd /tmp

apt-get purge -y docker docker.io* lxc-docker*
apt-get -yqq update
apt-get install -yqq apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
$(lsb_release -cs) stable"
apt-get -yqq update
apt-get -y install docker-ce

