#!/bin/bash
apt-get update
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
   "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF

apt-get update
apt-get install -yqq docker-ce=$(apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}')
apt-get install -yqq open-iscsi

# test snap
  if ! test_cmd_loc="$(type -p "snap")" || [ -z "$test_cmd_loc" ]; then
    echo "snap was not found in your path! skipping"
  else
    snap install --classic go
    go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
  fi

service open-iscsi restart
apt-mark hold docker-ce
apt-get install -yqq kubelet kubeadm kubectl
