#!/bin/bash
# Docker Machine
MACHINE_V=v0.13.0
curl -L https://github.com/docker/machine/releases/download/$MACHINE_V/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine
chmod +x /tmp/docker-machine
sudo mv /tmp/docker-machine /usr/local/bin/docker-machine
