#!/bin/bash
echo -n "Installing docker repos Ctrl-C now to exit"
for i in {1..5};do sleep 1; echo -n '!'; done
echo '!'
cd /tmp

# Redhat Specifics
yum update
curl -fsSL https://get.docker.com/ | sh
sudo service docker start
chkconfig docker on

# Docker Machine
curl -L https://github.com/docker/machine/releases/download/v0.5.0/docker-machine_linux-amd64.zip >machine.zip
unzip machine.zip
rm machine.zip
sudo mv docker-machine* /usr/local/bin

# Docker Compose
sudo curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
