#!/bin/bash
echo -n "Installing docker repos Ctrl-C now to exit"
for i in {1..5};do sleep 1; echo -n '!'; done
echo '!'
cd /tmp

sudo apt-get -yqq update
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    bridge-utils unzip bzip2 \
    software-properties-common \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get -yqq update

sudo apt-cache policy docker-engine
sudo apt-get install -yqq docker-ce
sudo service docker restart

# Docker Machine
curl -L https://github.com/docker/machine/releases/download/v0.10.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
chmod +x /tmp/docker-machine &&
sudo mv /tmp/docker-machine /usr/local/bin/docker-machine

# Docker Compose
curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
sudo chmod +x /tmp/docker-compose
sudo mv /tmp/docker-compose /usr/local/bin/docker-compose
