#!/bin/bash
echo -n "Installing docker repos Ctrl-C now to exit"
for i in {1..5};do sleep 1; echo -n '!'; done
echo '!'
cd /tmp

sudo apt-get remove -yqq docker docker-engine docker.io
sudo apt-get -yqq update
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    git \
    make \
    bridge-utils unzip bzip2 \
    software-properties-common \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get -yqq update

#sudo apt-cache policy docker-engine
sudo apt-get install -yqq docker-ce
sudo service docker restart

# Docker Machine
curl https://raw.githubusercontent.com/joshuacox/roustabout/master/MachineInstall | bash

# Docker Compose
curl https://raw.githubusercontent.com/joshuacox/roustabout/master/ComposeInstall | bash

# Roustabout
curl https://raw.githubusercontent.com/joshuacox/roustabout/master/bootstraproustabout.sh|bash
